"use client";

export const dynamic = "force-dynamic";

import Link from "next/link";
import {
  ArrowRight,
  Bot,
  CalendarClock,
  CreditCard,
  Gem,
  LineChart,
  MessageSquareText,
  ShieldCheck,
  Sparkles,
  Target,
  UsersRound,
} from "lucide-react";
import { Skeleton, StatusPill } from "@/components/ui";

const OUTPUT_GROUPS = [
  {
    title: "Lifecycle output",
    hint: "Rule-based customer state from prediction output",
    icon: UsersRound,
    accent: "var(--moby-600)",
    fields: ["lifecycle_stage", "sub_stage", "days_since_last_activity", "ever_paid"],
  },
  {
    title: "Churn output",
    hint: "Churn score and business-friendly risk bucket",
    icon: Target,
    accent: "var(--danger)",
    fields: ["churn_probability", "churn_risk_level", "revenue_at_risk"],
  },
  {
    title: "CLV / value output",
    hint: "Six-month value estimate and payment summary",
    icon: Gem,
    accent: "#d97706",
    fields: ["predicted_clv_6m", "customer_value_tier", "n_purchases", "total_revenue", "avg_transaction_value"],
  },
  {
    title: "Credit forecast output",
    hint: "Credit usage and top-up timing signals",
    icon: CreditCard,
    accent: "#6d28d9",
    fields: ["predicted_credit_usage_30d", "predicted_credit_usage_90d", "estimated_days_until_topup", "credit_urgency_level", "usage_trend"],
  },
  {
    title: "Action output",
    hint: "Prioritization and next-best-action fields",
    icon: CalendarClock,
    accent: "var(--ok)",
    fields: ["priority_score", "priority_reason", "recommended_action", "recommended_followup_date"],
  },
  {
    title: "AI output",
    hint: "Persisted AI text only when generated by the pipeline",
    icon: Bot,
    accent: "var(--info)",
    fields: ["ai_status", "ai_explanation", "ai_reasoning_json", "ai_recommended_message", "ai_generated_at", "ai_model"],
  },
  {
    title: "Lineage / eligibility",
    hint: "Trace which models were eligible and used",
    icon: ShieldCheck,
    accent: "var(--ink-3)",
    fields: ["output_status", "output_notes", "model_eligibility_json", "model_versions_json", "created_at"],
  },
] as const;

const PREVIEW_COLUMNS = [
  "acc_id",
  "lifecycle_stage",
  "churn_probability",
  "predicted_clv_6m",
  "predicted_credit_usage_30d",
  "priority_score",
  "recommended_action",
  "output_status",
] as const;

export default function Dashboard() {
  return (
    <main className="px-8 py-6 pb-12 space-y-6">
      <section
        className="relative overflow-hidden rounded-[30px] border border-white/20 px-6 py-6 text-white sm:px-7 lg:px-8"
        style={{
          backgroundImage: [
            "radial-gradient(rgba(7, 29, 126, 0.52) 0%, transparent 42%)",
            "url(/assets/intro/about_bg.webp)",
            "linear-gradient(180deg, rgba(0,0,0,0.24) 0%, rgba(0,0,0,0.04) 38%, rgba(0,0,0,0.16) 100%)",
            "linear-gradient(140deg, #1d1f2a -10%, #006bff 57%, #1893f0 72%, #ffa400 87%, #fc4c02 97%)",
          ].join(", "),
          backgroundRepeat: "no-repeat, no-repeat, no-repeat, no-repeat",
          backgroundSize: "140% 150%, cover, 100% 100%, 100% 100%",
          backgroundPosition: "center, center, center, center",
        }}
      >
        <div className="absolute inset-0 bg-[linear-gradient(120deg,rgba(255,255,255,0.10),transparent_45%)]" />
        <div className="relative">
          <div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between">
            <div className="space-y-5">
              <div className="flex flex-wrap items-center gap-2">
                <StatusPill tone="info">ML v2 output</StatusPill>
                <StatusPill tone="neutral" dot={false}>UI only</StatusPill>
              </div>

              <div className="max-w-3xl">
                <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-white/68">
                  Prediction output dashboard
                </p>
                <h1 className="mt-2 text-3xl font-semibold leading-tight tracking-[-0.04em] sm:text-[42px]">
                  Dashboard
                </h1>
                <p className="mt-3 max-w-2xl text-sm leading-6 text-white/78 sm:text-[15px]">
                  แสดงเฉพาะ output fields ที่ระบบ ML v2 จะเขียนจริงใน `ml_prediction_outputs`
                  โดยค่าข้อมูลจริงยังเป็น skeleton จนกว่าจะเชื่อม API
                </p>
              </div>
            </div>

            <div className="flex flex-wrap gap-3 xl:justify-end">
              <Link
                href="/customers"
                className="inline-flex h-11 items-center gap-2 rounded-2xl border border-white/20 bg-white/96 px-4 text-[13px] font-semibold text-slate-900"
              >
                Customers <ArrowRight size={13} />
              </Link>
              <Link
                href="/playbooks"
                className="inline-flex h-11 items-center gap-2 rounded-2xl border border-white/22 bg-white/12 px-4 text-[13px] font-semibold text-white"
              >
                Action queue <ArrowRight size={13} />
              </Link>
            </div>
          </div>
        </div>
      </section>

      <section className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
        <MetricShell icon={UsersRound} label="Output rows" hint="prediction_run_id scope" />
        <MetricShell icon={LineChart} label="Scored churn rows" hint="churn_probability present" />
        <MetricShell icon={CreditCard} label="Credit forecast rows" hint="30d / 90d usage present" />
        <MetricShell icon={Sparkles} label="AI enriched rows" hint="ai_status generated" />
      </section>

      <section className="grid grid-cols-1 gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(360px,0.85fr)]">
        <div className="surface-elev overflow-hidden">
          <PanelTitle
            eyebrow="Output groups"
            title="Fields available on each prediction row"
            hint="Grouped by how the business will read the ML v2 output"
          />
          <div className="grid grid-cols-1 gap-4 border-t border-[color:var(--line-2)] p-5 lg:grid-cols-2">
            {OUTPUT_GROUPS.map((group) => (
              <OutputGroupCard key={group.title} group={group} />
            ))}
          </div>
        </div>

        <div className="space-y-5">
          <div className="surface-elev overflow-hidden">
            <PanelTitle
              eyebrow="Readiness"
              title="Output readiness"
              hint="Expected quality gates before interpreting rows"
            />
            <div className="space-y-4 border-t border-[color:var(--line-2)] p-5">
              <ReadinessRow label="Prediction run selected" />
              <ReadinessRow label="Output rows written" />
              <ReadinessRow label="Model lineage attached" />
              <ReadinessRow label="AI generation complete" />
            </div>
          </div>

          <div className="surface-elev overflow-hidden">
            <PanelTitle
              eyebrow="Actions"
              title="What this dashboard should drive"
              hint="No fake queue counts until real rows exist"
            />
            <div className="space-y-3 border-t border-[color:var(--line-2)] p-5">
              <ActionShell icon={Target} title="Prioritize outreach" fields="priority_score, priority_reason" />
              <ActionShell icon={MessageSquareText} title="Prepare message" fields="ai_recommended_message" />
              <ActionShell icon={CalendarClock} title="Schedule follow-up" fields="recommended_followup_date" />
            </div>
          </div>
        </div>
      </section>

      <section className="surface-elev overflow-hidden">
        <PanelTitle
          eyebrow="Preview"
          title="Prediction output row preview"
          hint="Table shape only. Cells stay skeleton until API is wired."
        />
        <div className="overflow-x-auto border-t border-[color:var(--line-2)]">
          <table className="table-base">
            <thead>
              <tr>
                {PREVIEW_COLUMNS.map((column) => (
                  <th key={column}>{column}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {Array.from({ length: 6 }).map((_, rowIndex) => (
                <tr key={rowIndex}>
                  {PREVIEW_COLUMNS.map((column, colIndex) => (
                    <td key={column}>
                      <Skeleton className={colIndex === 0 ? "h-4 w-16" : "h-4 w-28"} />
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </main>
  );
}

function MetricShell({
  icon: Icon,
  label,
  hint,
}: {
  icon: React.ElementType;
  label: string;
  hint: string;
}) {
  return (
    <div className="surface p-5">
      <div className="flex items-start justify-between gap-3">
        <div>
          <div className="text-[11px] font-semibold uppercase tracking-[.10em] text-[color:var(--ink-5)]">
            {label}
          </div>
          <Skeleton className="mt-3 h-8 w-24" />
        </div>
        <Icon size={17} className="text-[color:var(--moby-600)]" />
      </div>
      <div className="mt-3 text-[11.5px] text-[color:var(--ink-5)]">{hint}</div>
    </div>
  );
}

function OutputGroupCard({
  group,
}: {
  group: (typeof OUTPUT_GROUPS)[number];
}) {
  const Icon = group.icon;

  return (
    <div className="rounded-[22px] border border-[color:var(--line)] bg-white p-4">
      <div className="flex items-start gap-3">
        <span
          className="grid h-9 w-9 shrink-0 place-items-center rounded-xl"
          style={{ background: "var(--surface-2)", color: group.accent }}
        >
          <Icon size={16} />
        </span>
        <div className="min-w-0 flex-1">
          <h3 className="text-[13px] font-semibold text-[color:var(--ink-1)]">{group.title}</h3>
          <p className="mt-1 text-[12px] leading-5 text-[color:var(--ink-4)]">{group.hint}</p>
        </div>
      </div>
      <div className="mt-4 flex flex-wrap gap-2">
        {group.fields.map((field) => (
          <code
            key={field}
            className="rounded-lg border border-[color:var(--line)] bg-[color:var(--surface-2)] px-2 py-1 text-[11px] text-[color:var(--ink-3)]"
          >
            {field}
          </code>
        ))}
      </div>
      <div className="mt-4 space-y-2">
        <Skeleton className="h-3 w-full" />
        <Skeleton className="h-3 w-4/5" />
      </div>
    </div>
  );
}

function PanelTitle({
  eyebrow,
  title,
  hint,
}: {
  eyebrow: string;
  title: string;
  hint: string;
}) {
  return (
    <header className="flex items-start justify-between gap-4 px-5 py-4">
      <div>
        <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-[color:var(--ink-5)]">
          {eyebrow}
        </p>
        <h2 className="mt-1 text-[17px] font-semibold tracking-[-0.02em] text-[color:var(--ink-1)]">
          {title}
        </h2>
        <p className="mt-1 text-[12px] leading-5 text-[color:var(--ink-4)]">{hint}</p>
      </div>
    </header>
  );
}

function ReadinessRow({ label }: { label: string }) {
  return (
    <div className="flex items-center gap-3">
      <Skeleton className="h-5 w-5 rounded-full" />
      <div className="min-w-0 flex-1">
        <div className="text-[12.5px] font-medium text-[color:var(--ink-2)]">{label}</div>
        <Skeleton className="mt-1.5 h-2 w-full rounded-full" />
      </div>
    </div>
  );
}

function ActionShell({
  icon: Icon,
  title,
  fields,
}: {
  icon: React.ElementType;
  title: string;
  fields: string;
}) {
  return (
    <div className="rounded-xl border border-[color:var(--line)] bg-white p-3">
      <div className="flex items-start gap-3">
        <Icon size={15} className="mt-0.5 text-[color:var(--moby-600)]" />
        <div className="min-w-0">
          <div className="text-[12.5px] font-semibold text-[color:var(--ink-1)]">{title}</div>
          <div className="mt-1 text-[11px] text-[color:var(--ink-5)]">{fields}</div>
        </div>
      </div>
    </div>
  );
}

function SchemaLine({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl bg-white px-3 py-2.5">
      <div className="text-[10px] font-semibold uppercase tracking-[.12em] text-[color:var(--ink-5)]">
        {label}
      </div>
      <div className="mt-1 text-[12px] font-medium text-[color:var(--ink-2)]">{value}</div>
    </div>
  );
}
